import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
  ],
  theme: {
    container: { center: true, padding: '1.5rem', screens: { '2xl': '1400px' } },
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        border:      'hsl(var(--border))',
        input:       'hsl(var(--input))',
        ring:        'hsl(var(--ring))',
        background:  'hsl(var(--background))',
        foreground:  'hsl(var(--foreground))',
        primary:     { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary:   { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        muted:       { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent:      { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        popover:     { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        card:        { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        brand: {
          50:  '#eef0ff',
          100: '#dde2ff',
          200: '#c3caff',
          300: '#9ea8ff',
          400: '#7b83ff',
          500: '#6271f6',
          600: '#4c56e8',
          700: '#3d46ce',
          800: '#333ba7',
          900: '#2e3683',
          950: '#1c2054',
        },
        success:  { DEFAULT: '#10b981', foreground: '#ffffff' },
        warning:  { DEFAULT: '#f59e0b', foreground: '#ffffff' },
        info:     { DEFAULT: '#3b82f6', foreground: '#ffffff' },
      },
      borderRadius: {
        sm:   'calc(var(--radius) - 4px)',
        md:   'calc(var(--radius) - 2px)',
        lg:   'var(--radius)',
        xl:   'calc(var(--radius) + 4px)',
        '2xl':'calc(var(--radius) + 8px)',
        '3xl':'calc(var(--radius) + 16px)',
        full: '9999px',
      },
      spacing: { 18: '4.5rem', 22: '5.5rem', 26: '6.5rem' },
      boxShadow: {
        'brand':    '0 8px 32px -8px rgb(98 113 246 / 0.4)',
        'brand-lg': '0 20px 60px -12px rgb(98 113 246 / 0.5)',
        'card':     '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        'card-hover': '0 10px 40px -8px rgb(0 0 0 / 0.15)',
        'glow':     '0 0 40px rgb(98 113 246 / 0.15)',
        'inner-brand': 'inset 0 1px 0 0 rgb(255 255 255 / 0.08)',
      },
      backgroundImage: {
        'gradient-brand':   'linear-gradient(135deg, #6271f6 0%, #8198fb 100%)',
        'gradient-dark':    'linear-gradient(135deg, #0d0f1a 0%, #1a1d35 100%)',
        'gradient-radial':  'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':   'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'glass-gradient':   'linear-gradient(135deg, rgba(255,255,255,0.08), rgba(255,255,255,0.02))',
        'hero-gradient':    'radial-gradient(ellipse 80% 60% at 50% -10%, rgba(98,113,246,0.18), transparent 70%)',
      },
      keyframes: {
        'fade-in':           { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'fade-in-fast':      { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-up':          { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in-right':    { from: { opacity: '0', transform: 'translateX(20px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'slide-in-left':     { from: { opacity: '0', transform: 'translateX(-20px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'scale-in':          { from: { opacity: '0', transform: 'scale(0.94)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'float':             { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        'shimmer':           { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'pulse-brand':       { '0%,100%': { opacity: '1', boxShadow: '0 0 0 0 rgba(98,113,246,0)' }, '50%': { boxShadow: '0 0 0 8px rgba(98,113,246,0)' } },
        'spin-slow':         { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        'bounce-subtle':     { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-4px)' } },
        'gradient-shift':    { '0%,100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        'accordion-down':    { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':      { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'fade-in':        'fade-in 0.4s ease-out forwards',
        'fade-in-fast':   'fade-in-fast 0.2s ease-out forwards',
        'slide-up':       'slide-up 0.5s ease-out forwards',
        'slide-up-delay': 'slide-up 0.5s ease-out 0.15s forwards',
        'slide-in-right': 'slide-in-right 0.4s ease-out forwards',
        'slide-in-left':  'slide-in-left 0.4s ease-out forwards',
        'scale-in':       'scale-in 0.3s ease-out forwards',
        'float':          'float 5s ease-in-out infinite',
        'shimmer':        'shimmer 2s linear infinite',
        'spin-slow':      'spin-slow 8s linear infinite',
        'bounce-subtle':  'bounce-subtle 2s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 4s ease infinite',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}

export default config
